/**
 * Build artifacts page (/builds/:buildId/artifacts).
 *
 * Displays manifest summarization, downloadable file list, and original manifest (JSON) (proposal §5.7, #30).
 *
 * Manifest summarization/JSON is fetched from `GET /builds/{run_id}/manifest`, while **downloadable
 * file list is fetched separately from `GET /artifacts/{run_id}`**. The two calls are independent,
 * so failure in one doesn't block the other. Downloads use only the canonical run-relative paths
 * from the `/artifacts/{run_id}` list — `manifest.outputs` is an absolute storage path and cannot
 * be used as a download identifier. Some legacy/partial runs may lack metadata fields in the manifest;
 * in such cases, we display factually that "some metadata is unavailable". Mock mode uses deterministic fixtures.
 */
import { useTranslation } from "react-i18next";
import { i18n } from "@/shared/i18n";
import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import {
  downloadArtifact,
  getBuildManifest,
  listArtifactFiles,
  saveBlobAsFile,
} from "@/features/artifacts/api";
import type { BuildManifest } from "@/shared/lib/types";
import { Button, Card, EmptyState, ErrorState, LinkButton, PageHeader, SkeletonTable } from "@/shared/ui";

interface ManifestState {
  status: "loading" | "loaded" | "error";
  manifest?: BuildManifest;
  error?: string;
}

type ArtifactsState =
  | { status: "loading" }
  | { status: "loaded"; files: string[] }
  | { status: "error"; error: string };

/** Extract display name and format (extension) from file path. */
function describeFile(path: string): { name: string; format: string } {
  const name = path.split(/[\\/]/).pop() ?? path;
  const dot = name.lastIndexOf(".");
  return { name, format: dot >= 0 ? name.slice(dot + 1) : "—" };
}

type RowDownloadState =
  | { status: "idle" }
  | { status: "downloading" }
  | { status: "error"; message: string };

/**
 * Single artifact file row. `path` is the canonical run-relative POSIX path from
 * `GET /artifacts/{run_id}`. Download uses the exact run_id + this path in an authenticated
 * Builder request (`downloadArtifact`) and saves the result as a Blob. During download, the button
 * is disabled to prevent duplicate clicks, and errors are displayed only for this row — not for
 * the entire page.
 */
function ArtifactRow({ runId, path }: { runId: string; path: string }) {
  const { t } = useTranslation();
  const { name, format } = describeFile(path);
  const [state, setState] = useState<RowDownloadState>({ status: "idle" });

  const onDownload = useCallback(() => {
    if (state.status === "downloading") return;
    setState({ status: "downloading" });
    downloadArtifact(runId, path)
      .then(({ blob, filename }) => {
        saveBlobAsFile(blob, filename);
        setState({ status: "idle" });
      })
      .catch((cause: unknown) => {
        setState({
          status: "error",
          message: cause instanceof Error ? cause.message : i18n.t("artifacts.errors.download"),
        });
      });
  }, [runId, path, state.status]);

  return (
    <li className="grid grid-cols-[1.6fr_0.6fr_0.8fr] items-center gap-4 border-b border-border px-6 py-3 text-sm last:border-0">
      <span className="break-all font-medium">{name}</span>
      <span className="uppercase text-muted-foreground">{format}</span>
      <span className="flex flex-col items-start gap-1">
        <Button
          size="sm"
          variant="secondary"
          loading={state.status === "downloading"}
          disabled={state.status === "downloading"}
          onClick={onDownload}
        >
          {t("artifacts.files.download")}
        </Button>
        {state.status === "error" ? (
          <span role="alert" className="text-xs text-red-600 dark:text-red-400">
            {state.message}
          </span>
        ) : null}
      </span>
    </li>
  );
}

/**
 * Page displaying artifacts and manifest summary generated by a build.
 *
 * @returns Artifacts screen.
 */
export function BuildArtifactsPage() {
  const { t } = useTranslation();
  const { buildId = "" } = useParams();
  const [state, setState] = useState<ManifestState>({ status: "loading" });
  const [artifacts, setArtifacts] = useState<ArtifactsState>({ status: "loading" });

  const load = useCallback(() => {
    const controller = new AbortController();
    setState({ status: "loading" });
    setArtifacts({ status: "loading" });
    getBuildManifest(buildId, controller.signal)
      .then((manifest) => {
        if (!controller.signal.aborted) setState({ status: "loaded", manifest });
      })
      .catch((cause: unknown) => {
        if (controller.signal.aborted) return;
        setState({
          status: "error",
          error: cause instanceof Error ? cause.message : i18n.t("artifacts.errors.manifest"),
        });
      });
    // Downloadable file list is fetched separately from canonical `GET /artifacts/{run_id}`
    // (manifest.outputs is an absolute storage path and cannot be used as download identifier).
    // Manifest loading and file listing are independent, so failure in one doesn't block the other.
    listArtifactFiles(buildId, controller.signal)
      .then((files) => {
        if (!controller.signal.aborted) setArtifacts({ status: "loaded", files });
      })
      .catch((cause: unknown) => {
        if (controller.signal.aborted) return;
        setArtifacts({
          status: "error",
          error: cause instanceof Error ? cause.message : i18n.t("artifacts.errors.files"),
        });
      });
    return () => controller.abort();
  }, [buildId]);

  useEffect(() => load(), [load]);

  const manifest = state.manifest;
   // If outputs is undefined, preserve formats as undefined; if empty array, preserve as empty array (#119)
  const formats = manifest?.outputs
    ? [...new Set(manifest.outputs.map((path) => describeFile(path).format))]
    : manifest?.outputs ?? undefined;
   // Builder provides row_counts per source (dict), so UI summary shows total.
   // If row_counts is not provided (undefined), display record count as "not provided".
  const totalRecords = manifest?.row_counts
    ? Object.values(manifest.row_counts).reduce((sum, count) => sum + count, 0)
    : undefined;
   // Legacy/partial manifest guidance: some runs may lack metadata fields in manifest.
  const hasMetadata =
    manifest?.row_counts !== undefined && manifest?.provenance !== undefined;

  return (
    <main className="flex flex-1 flex-col gap-6 px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
      <PageHeader
        eyebrow={t("artifacts.page.eyebrow")}
        title={t("artifacts.page.title", { build: buildId || "Build" })}
        description={t("artifacts.page.desc")}
        actions={<LinkButton to={`/builds/${buildId}/publish`}>{t("artifacts.page.publish")}</LinkButton>}
      />

      {state.status === "loading" ? (
        <Card className="p-0">
          <SkeletonTable rows={4} />
        </Card>
      ) : null}

      {state.status === "error" ? (
        <Card variant="error" className="p-0">
          <ErrorState
            title={t("artifacts.errors.loadTitle")}
            message={state.error}
            onRetry={() => load()}
          />
        </Card>
      ) : null}

      {state.status === "loaded" && manifest ? (
        <>
          <Card>
            <p className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              {t("artifacts.manifest.summary")}
            </p>
            <dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4">
              <div>
                <dt className="text-muted-foreground">{t("artifacts.manifest.records")}</dt>
                <dd className="text-foreground">
                  {totalRecords !== undefined
                    ? totalRecords.toLocaleString("ko-KR")
                    : i18n.t("artifacts.manifest.notProvided")}
                </dd>
              </div>
              <div>
                <dt className="text-muted-foreground">{t("artifacts.manifest.formats")}</dt>
                <dd className="text-foreground">
                  {formats === undefined
                    ? t("buildArtifacts.notProvided")
                    : formats.length > 0
                      ? formats.join(", ")
                      : t("buildArtifacts.noExports")}
                </dd>
              </div>
              <div>
                <dt className="text-muted-foreground">{t("artifacts.manifest.sources")}</dt>
                <dd className="text-foreground">
                  {manifest.provenance === undefined
                    ? t("buildArtifacts.notProvided")
                    : manifest.provenance.length > 0
                      ? manifest.provenance.map((p) => `${p.provider}.${p.dataset}`).join(", ")
                      : t("buildArtifacts.noSources")}
                </dd>
              </div>
              <div>
                <dt className="text-muted-foreground">{t("artifacts.manifest.buildId")}</dt>
                <dd className="break-all text-foreground">{manifest?.build_id || i18n.t("artifacts.manifest.notProvided")}</dd>
              </div>
            </dl>
          </Card>

          <Card className="p-0">
            <div className="grid grid-cols-[1.6fr_0.6fr_0.8fr] gap-4 border-b border-border px-6 py-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              <span>{t("artifacts.files.title")}</span>
              <span>{t("artifacts.files.format")}</span>
              <span>{t("artifacts.files.action")}</span>
            </div>
            {artifacts.status === "loading" ? (
              <SkeletonTable rows={4} />
            ) : artifacts.status === "error" ? (
              <EmptyState title={t("artifacts.errors.files")} description={artifacts.error} />
            ) : artifacts.files.length === 0 ? (
              <EmptyState title={t("artifacts.files.emptyTitle")} />
            ) : (
              <ul>
                {artifacts.files.map((path) => (
                  <ArtifactRow key={path} runId={buildId} path={path} />
                ))}
              </ul>
            )}
          </Card>

          <Card>
            <p className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              manifest.json
            </p>
            {!hasMetadata && (
              <p className="mt-2 text-xs text-amber-600 dark:text-amber-400">
                {t("buildArtifacts.partialManifest")}
              </p>
            )}
            <pre className="mt-4 overflow-x-auto rounded-xl bg-zinc-950 p-4 text-xs leading-6 text-zinc-100">
              <code>{JSON.stringify(manifest, null, 2)}</code>
            </pre>
          </Card>
        </>
      ) : null}
    </main>
  );
}
