/**
 * Report data model (#258).
 *
 * Every block in a Report has exactly one of three fixed provenances — a
 * value taken verbatim from Builder (BUILDER_EVIDENCE), an interpretation
 * generated by Kubi (KUBI_INTERPRETATION), or content written by the user
 * (USER_CONTENT). The three are never stored blended in one representation
 * (#258 review §2) — BUILDER_EVIDENCE blocks are produced only by
 * deterministic code, and users leave their own notes only in separate
 * USER_CONTENT blocks.
 *
 * A Report stores the dataset/run (`datasetId`/`baseRunId`) chosen at
 * creation time, pinned. A new Run never rewrites it automatically (#258
 * review §1) — `staleness.ts` compares the stored basis against current
 * Builder state and judges only CURRENT/STALE/ORPHAN/UNAVAILABLE.
 */

/** Provenance of a Report block. Discriminator tag so the three kinds are never blended in one representation. */
export type BlockProvenance = "BUILDER_EVIDENCE" | "KUBI_INTERPRETATION" | "USER_CONTENT";

interface BaseBlock {
  id: string;
  provenance: BlockProvenance;
  createdAt: string;
  updatedAt: string;
}

/** Deterministic section kind. Filled only from Builder evidence; never LLM-generated. */
export type BuilderEvidenceSection =
  | "overview"
  | "pipeline"
  | "quality"
  | "schema"
  | "data_summary"
  | "output";

/**
 * Block assembled verbatim from Builder evidence by code. Fields with no
 * value or a failed lookup render as "N/A"/"unavailable" — never silently
 * replaced with 0/PASS/normal (#258 §4). Not user-editable — so actual and
 * user-edited values are never blended indistinguishably (#258 §10). To
 * rebuild, refresh the evidence and regenerate.
 */
export interface BuilderEvidenceBlock extends BaseBlock {
  provenance: "BUILDER_EVIDENCE";
  section: BuilderEvidenceSection;
  title: string;
  /** Rendered safe plain-text/markdown body (generated by code, not the user's raw input). */
  markdown: string;
  /** Whether the evidence lookups this section depended on all succeeded, partially failed, or all failed. */
  evidenceStatus: "ok" | "partial" | "unavailable";
  /** Human-readable reason when unavailable/partial (to prompt a retry). */
  unavailableReason?: string;
  /**
   * Body summarizing the `markdown` (detailed evidence table) as
   * deterministic sentences (#258 IA rework). `narrativeSummary.ts`
   * verbalizes the evidence as-is; missing values are written as "cannot be
   * determined" — never dressed up as 0/PASS. Optional because Reports
   * saved before this field existed may lack it; the renderer then shows
   * only the detailed table.
   */
  summary?: string;
  /**
   * Aggregate filled only when section is "quality" AND real Builder
   * quality evidence exists. Left unset when availability=unavailable or
   * the quality lookup itself failed (no fake zeros) — used by the Quality
   * summary in the Report Context sidebar.
   */
  qualityCounts?: { pass: number; warn: number; fail: number; evaluated: number };
}

/**
 * An interpretation block Kubi proposed (ADD_REPORT_BLOCK) and the user accepted (#258 §6, §7).
 *
 * `sourceContext` is the dataset/run/stage at the time this note was
 * created — it may differ from the Report's base, and when it does,
 * `isSameContext=false` marks it as a "reference analysis" (an analysis of
 * another Run is never merged as if it were this Report's canon).
 */
export interface KubiInterpretationBlock extends BaseBlock {
  provenance: "KUBI_INTERPRETATION";
  note: string;
  reason: string;
  sourceContext: { datasetId?: string; runId?: string; stage?: string };
  /** Whether sourceContext matches this Report's datasetId/baseRunId. */
  isSameContext: boolean;
  /** When the ADD_REPORT_BLOCK was queued (treated as when Kubi produced the answer). */
  generatedAt: string;
  /** Detailed evidence such as evidenceRefs is not kept by reportInbox; fill only when available. */
  provider?: string;
  model?: string;
}

/** Free-form block written or edited directly by the user. */
export interface UserContentBlock extends BaseBlock {
  provenance: "USER_CONTENT";
  heading: string;
  markdown: string;
}

export type ReportBlock = BuilderEvidenceBlock | KubiInterpretationBlock | UserContentBlock;

/** Verdict on whether the basis evidence is still valid when a saved Report is reopened (#258 §8). */
export type EvidenceRunStatus = "current" | "stale" | "orphan" | "unavailable";

/** Stable reference to an evidence fragment a Report cites (for export/re-verification). */
export interface ReportEvidenceRef {
  kind: "dataset" | "run" | "quality" | "schema" | "stage" | "output";
  id: string;
  label: string;
}

/**
 * The stored Report Draft. `id` is unique within the store; `datasetId`/
 * `baseRunId` are pinned at creation and never change through later edits
 * (only a separate "rebuild against a new Run" flow creates a new Report).
 */
export interface ReportDraft {
  id: string;
  title: string;
  datasetId: string;
  baseRunId: string;
  /** spec_digest from the run lookup, when present. Builder does not persist specs, so it can be null. */
  buildSpecDigest: string | null;
  createdAt: string;
  updatedAt: string;
  /** When the evidence fill of this Report's BUILDER_EVIDENCE blocks last ran. */
  evidenceFetchedAt: string;
  /** Report envelope schema version (per Report, independent of the store envelope version). */
  version: number;
  /** Optimistic-concurrency counter to detect saves from another tab of the same browser (#258 §13 minimal safety). */
  revision: number;
  blocks: ReportBlock[];
  evidenceRefs: ReportEvidenceRef[];
}

/** Minimal summary for the Report list screen (listing without loading full blocks). */
export interface ReportSummary {
  id: string;
  title: string;
  datasetId: string;
  baseRunId: string;
  createdAt: string;
  updatedAt: string;
}

export const REPORT_VERSION = 1;
